CREATE SEQUENCE COLABORADORES_SEQ;
START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_COLABORADOR (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR2(50),
    email VARCHAR2(50) UNIQUE NOT NULL,
    senha VARCHAR2(50) NOT NULL,
    risco_emocional VARCHAR (50),
    data_nascimento DATE
);